source 'https://rubygems.org'

gem 'redcarpet'
gem 'rake'
gem 'rack'
gem 'rspec'
gem 'pry'
gem 'ctags_reader', :github => 'AndrewRadev/ctags_reader'
gem 'ruby-graphviz'
gem 'sinatra'
gem 'shotgun'
gem 'erubis'
